Repository src-d/gitbase-web, pull requests merged in 2018-05, with the labels that each got.

#14 Add some tests to be used by the CI
  server/common_test.go
  server/handler/query.go
  server/handler/query_test.go
  server/handler/tables.go
  server/handler/tables_test.go
  server/router.go
  server/router_test.go
  server/serializer/serializers_test.go
  server/service/common.go
  server/service/common_test.go
Labels: enhancement, new feature

#15 Add CI, docs and fix integration tests
  .dockerignore
  .github/CODE_OF_CONDUCT.md
  .github/DCO
  .github/screenshot.png
  .travis.yml
  Dockerfile
  Makefile
  README.md
  cmd/gitbase-playground/main.go
  docs/CONTRIBUTING.md
  docs/quickstart.md
  server/assets/asset.go.bak
  server/common_test.go
  server/handler/common_test.go
  server/handler/query_integration_test.go
  server/handler/query_uast_integration_test.go
  server/handler/tables_integration_test.go
  server/handler/tables_test.go
  server/router_test.go
  server/service/common.go
  server/testing/common.go
Labels: enhancement, new feature

#16 Simple UI
  frontend/.eslintrc.js
  frontend/.gitignore
  frontend/.prettierrc
  frontend/config-overrides.js
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/manifest.json
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/api.js
  frontend/src/components/QueryBox.js
  frontend/src/components/QueryBox.less
  frontend/src/components/ResultsTable.js
  frontend/src/components/ResultsTable.less
  frontend/src/index.js
  frontend/src/index.less
  frontend/src/override.less
  frontend/src/setupTests.js
  frontend/yarn.lock
Labels: new feature

#30 Add frontend assets into single binary
  Makefile
  cmd/gitbase-playground/main.go
  docs/quickstart.md
  public/index.html
  public/secondary.html
Labels: new feature

#31 Fix static 404
  server/handler/static_files.go
Labels: bug, enhancement

#33 Add docker-compose
  Makefile
  docker-compose.build.yml
  docker-compose.yml
  docs/quickstart-manually.md
  docs/quickstart.md
Labels: enhancement
